### PR TITLE
Add Pie Chart Type & Stack Percent Bar Charts

### PR DESCRIPTION
**Pull request by jrking4**
Add Non 3D Pie Chart Type
Add Grouping Option to Bar Charts - To allow for Stack and Percent Stacked Charts

### CODE REVIEW

**Comment by Progi1984** [comment]
@jrking4 Good job for your pull request (very)... Could you look into implementing these improvements in the ODPresentation writer ? and improve Sample_05 ?

**Comment by jrking4** [comment]
@Progi1984 No problem & glad to contribute. Sample_05 is updated. ODPresentation Writer should work with new chart types.

**Comment by Progi1984** [comment]
@jrking4 Perfect.... For finishing, could you add a line to changelog.md ?

**Comment by Progi1984** [comment]
@jrking4 I will add it ;)

**Pull request merged**
